name: Build APK with EAS
on: [workflow_dispatch]
jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Install EAS CLI
        run: npm install -g eas-cli
      - name: Generate and Commit Signature
        run: |
          keytool -genkey -v -keystore keystore.jks -alias key -keyalg RSA -keysize 2048 -validity 10000 -storepass password123 -keypass password123 -dname "CN=Saar Player, OU=App, O=Aniket, C=IN"
          echo '{ "android": { "keystore": { "keystorePath": "keystore.jks", "keystorePassword": "password123", "keyAlias": "key", "keyPassword": "password123" } } }' > credentials.json
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add keystore.jks credentials.json
          git commit -m "Add digital signature"
      - name: Install Dependencies
        run: npm install
      - name: Build Android APK
        run: eas build --platform android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
